### ISSUE TITLE
Use Piping Server for video live streaming or undetermined number of receivers

### ISSUE THREAD

**Issue by kelvin2200** [nwtgck/piping-server-pkg#132]
This is more of a question than an issue, and I'm fairly sure it's not possible with piping server, but I will ask anyway.
Is it possible to use piping server to achieve a live video streaming mechanism?
Say for example: the server reads from a local video file, or receives it's data via some stream then creates a url that multiple (undefined number) of viewers can access?

**Comment by nwtgck** [comment]
Hi, It may be this: https://github.com/nwtgck/piping-server-rust/issues/267#issuecomment-1140285698.
