### ISSUE TITLE
What's the difference of linuxstatic and linux ?

### ISSUE THREAD

**Issue by m2acgi** [nwtgck/piping-server-pkg#134]
What's the difference of piping-server-pkg-linuxstatic-x64.tar.gz and piping-server-pkg-linux-x64.tar.gz? Which one should I choose to use ? Thanks.

**Comment by nwtgck** [comment]
I always use linuxstatic and it works fine.

linuxstatic is a fullly static binary. You can see vercel/pkg to know the difference:

> Note that fully static Node binaries are not capable of loading native bindings, so you may not use Node bindings with linuxstatic.

https://github.com/vercel/pkg/tree/614c02a06830e0a4a898e6cf4eb35dbbf6110af3#native-addons

**Comment by m2acgi** [comment]
Thanks.
