### ISSUE TITLE
How to run Windows package

### ISSUE THREAD

**Issue by TopWebFullDev** [nwtgck/piping-server-pkg#83]
I can't run the windows portable package.

**Comment by nwtgck** [comment]
Hi. Could you tell what kind of error did you have?

**Comment by nwtgck** [comment]
You may run `docker run -p 8080:8080 nwtgck/piping-server` on WSL(Windows Subsystem for Linux) on Windows 10.

**Comment by TopWebFullDev** [comment]
If I execute in cmd with port or not and double-click the package, it doesn't run. It may be a silly question, is there any proper way to open the Win package? Thank you.

**Comment by nwtgck** [comment]
Another way is running on command prompt using `.\piping-server-win.exe`. I think it shows some error.

**Comment by nwtgck** [comment]
Hi,

This issue was fixed on https://github.com/nwtgck/piping-server-pkg/commit/c030e58de7e03d76b31660db0fc472e82e5a20d4. I''ll create a new release.

**Comment by nwtgck** [comment]
I created a new release.

Try <https://github.com/nwtgck/piping-server-pkg/releases/download/v1.2.3/piping-server-win.exe>.

**Comment by TopWebFullDev** [comment]
Yes! It works perfectly!
Thank you so much.
